### ISSUE TITLE
Y-scroll when on bottom of the page

### ISSUE THREAD

**Issue by KamilPesek** [Vuepic/vue-datepicker#23]
**Describe the bug**
When there is no scroll on page  (y-axe) or when the input element is at the end of the page, during calendar opening scroll appears. It's because menu is going from down and as written before, there is nothing bellow therefore this menu makes page longer. 

**To Reproduce**
1. Install datepicker
2. Insert it to the end of the page and/or have a page without y-scroll
3. Click on input (open calendar)
4. See scroll error

**Desktop & mobile (please complete the following information):**
 - Firefox Developer edition, 100.0b7 (64-bit)

**Comment by Jasenkoo** [comment]
@KamilPesek Did you disable `autoPosition`, even if there is no space it should only flicker for a millisecond and not extend the page? I will fix that flicker if that is what you are referring to.

**Comment by KamilPesek** [comment]
No, I can't disable it. Because if I disable it it will go
from 
![image](https://user-images.githubusercontent.com/25612952/164390706-12e981ab-9e2d-4d01-82be-8a5a0e4e8279.png)
to
![image](https://user-images.githubusercontent.com/25612952/164390857-b94c3268-4df5-4a79-8003-2b91ea0a9ac7.png)

**Comment by ekkode** [comment]
This issue is present since v2.4.0 as I said here : https://github.com/Vuepic/vue3-date-time-picker/issues/97#issuecomment-1046025217

If you add a "Lorem Ipsum" in front of the component so that component is lower in page, is not working, as you can see here: 
https://stackblitz.com/edit/vuepic-vue-datepicker-jhtqsd?file=src%2Fcomponents%2FPlayground.vue

**Comment by Jasenkoo** [comment]
@ekkode Fixed it, it will be added in v3.2.0. You would need to replace :autoPosition="false" with `alt-position="true"` and add the `:teleport="#exampleModal"` since the wrapper element is fixed position wrapper, thus, standard calculating would not work here.

**Comment by ekkode** [comment]
This will work strating form v3.2.0? Because now as you can see there is an error showing: 
![image](https://user-images.githubusercontent.com/13104697/165282472-6a132464-2a62-4d9a-9b3b-068fd7d002b3.png)

**Comment by Jasenkoo** [comment]
@ekkode Yes, from v3.2.0

**Comment by ekkode** [comment]
@Jasenkoo 

I have updated to v3.2.0 and the error is still there 
![image](https://user-images.githubusercontent.com/13104697/166226965-5ad96903-8dfd-44bb-b09a-f0177c29bf54.png)

**Comment by Jasenkoo** [comment]
@ekkode Sry, slight adjustments, teleport is a string prop and auto-apply boolean

Here is the working [example](https://stackblitz.com/edit/vuepic-vue-datepicker-4fv9nc?file=src%2Fcomponents%2FPlayground.vue)
